### ISSUE TITLE
Testing Plan

### ISSUE THREAD

**Issue by TylerC0108** [cartercsm9/codeCrafters#29]

**Comment by Riomari1** [comment]
Mocha: Test framework for structuring and executing tests.
Chai: Assertion library for defining test expectations.
plus any other dependencies we end up needing.


Weather Data Retrieval Functions:
Test functions responsible for fetching weather data from the API.
Ensure that the functions handle different response statuses (success, error) appropriately.

Data Processing Functions:
Test functions responsible for processing raw weather data.
Verify that data is parsed correctly and relevant information (temperature, humidity, etc.) is extracted accurately.
Test for edge cases like missing or invalid data.

Utility Functions:
Test utility functions used across the application (e.g., date formatting, unit conversion).
Ensure that utility functions produce the expected output for different inputs.
